name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      scylladb:
        image: scylladb/scylla
        ports:
          - 9042:9042
        options: --health-cmd "cqlsh --debug" --health-interval 5s --health-retries 10
        volumes:
          - ${{ github.workspace }}:/workspace
    steps:
    - uses: actions/checkout@v2
    - name: Format check
      run: cargo fmt --verbose --all -- --check
    - name: Clippy check
      run: cargo clippy --verbose --examples --tests -- -D warnings
    - name: Cargo check without features
      run: cargo check --manifest-path "scylla/Cargo.toml" --features ""
    - name: Build
      run: cargo build --verbose --examples
    - name: Run tests
      run: cargo test --verbose
